apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoreDuringExecution:
       nodeSlectorTerms:
       - matchExpressions:
         - key: kubernetes.io/e2e-az-name
           operator: In
           vales:
           - e2e-az1
           - e2e-az2
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: another-node
    
